SumoLogic/fluentd-output-sumologic

fluent-plugin-sumologic_output.gemspec, lib/fluent/plugin/out_sumologic.rb
Raise an exception for all non HTTP Success response codes. Fluentd will detect this failed flush and schedule a retry later on. This is similar to memorycraft's implementation of the plugin.
Basically this fix is to address the Data Ingestion Throttling scenario, e.g.
/var/log/td-agent/td-agent.log
```
2017-05-09 17:27:07 +1000 [warn]: temporarily failed to flush the buffer. next_retry=2017-05-09 17:27:08 +1000 error_class="RuntimeError" error="Failed to send data to HTTP Source. 429 - You have temporarily exceeded your Sumo Logic quota. Please try again at a later time." plugin_id="object:3f9ef4920e64"
...
2017-05-09 17:39:07 +1000 [warn]: suppressed same stacktrace
2017-05-09 17:39:11 +1000 [warn]: retry succeeded. plugin_id="object:3f9ef4920e64"
```
As you can see, once the ingestion …
=> Raise an exception for all non HTTP Success response codes

README.md, fluent-plugin-sumologic_output.gemspec, lib/fluent/plugin/out_sumologic.rb
When the `path` key in `<source>` is a wildcard, i.e. /var/log/*, the SumoLogic plugin should attempt to retrieve the source name from FluentD's buffer record.
One could create N amount of `<match>` records with the appropriate source_name values to cater for each log file in /var/log/*, but that would be massive amounts of config duplication.
In the following example, you need to specify a path_key in the `<source>` section, i.e. source_name, and then in the `<match>` section, specify the same value for the `source_name_key` param. Whenever new messages arrive in FluentD's buffer, the plugin will extract the value of `source_name` from the buffer.
```
<source>
format none
message_key event
path /var/log/*
path_key source_name
...
tag fluent.var_log_star
@type tail
</source>
<match> …
```
=> Extract the source_name from FluentD's buffer

lib/fluent/plugin/out_sumologic.rb
Allow to dynamically expand parameters in the `sourceName`, `sourceCategory` and `sourceHost`  in the output configuration.
Example:
```
source_category ${record['ecs']['docker_name']}
source_name     ${tag_parts[0]} 
```
Closes Issue #9
=> Expand parameters in the output configuration

Gemfile, README.md, Rakefile, fluent-plugin-sumologic_output.gemspec, lib/fluent/plugin/out_sumologic.rb, test/helper.rb, test/plugin/test_out_sumologic.rb
In past http lib, the `open_timeout` default value is `nil`.
https://github.com/ruby/ruby/blob/v2_1_0/lib/net/http.rb#L644
And, some fluentd plugin has the option.
https://github.com/fluent/fluent-plugin-webhdfs
I think it is worthful to add.
=> add open_timeout option

README.md
Noticed a few warnings using the sample configuration:
```
2017-12-18 15:58:47 -0800 [warn]: 'type' is deprecated parameter name. use '@type' instead.
```
Tested with `@type` and it works correctly without warnings.
=> Avoid warnings for @type parameters

lib/fluent/plugin/out_sumologic.rb
Adds the `X-Sumo-Client` header as part of our initiative to track HTTP collection usage.
Verified the header is sent with log message payload.
=> Add client header for fluentd output

fluent-plugin-sumologic_output.gemspec
Current version of this plugin can't use in v0.12. ( #12 )
=> specify version of fluentd

README.md, lib/fluent/plugin/out_sumologic.rb
This allows #25 to happen. 
It accepts `proxy_uri` as a parameter in `match` and then we can use it in the `HTTPCLIENT` connetion. 
It does not allow for the `ENV` setting to be used *yet* as this is a quick fix that I need. 
MM
=> ISSUE #25: Adding proxy capability

README.md, fluent-plugin-sumologic_output.gemspec, lib/fluent/plugin/out_sumologic.rb, test/plugin/test_out_sumologic.rb
* Adds `timestamp_key` property, which allows the user to customize the default key of `timestamp` (+ tests)
* Changes merge order of `json_merge` so that the log message wins over the record data in cases of conflict (+ tests)
* Updates bundler to 2 (unrelated, required to run tests)
* Switching the symbol key (`{ :timestamp => 123 }`) to a string `{ 'timestamp' => 123 }` is important. `JSON.dump({ :foo => 'bar', 'foo' => 'qux' })` will return `{"foo:"bar","foo":"qux"}` so we need key types to match.
* The change in merge order is the most invasive but it seems sensible to prioritize user data over record data in the event of conflict. I doubt anyone has run into this yet and I had to write a failing test to understand how it works.
[Scoop](https://github.com/takescoop/) uses a standard …
=> Add "timestamp_key", prefer log message when merging

.gitignore, .travis.yml, ci/build.sh, fluent-plugin-sumologic_output.gemspec
Travis build randomly failure on missing bundler 2.x
add a before_install step to avoid it
also try to use a bash script to auto pop version string from `TRAVIS_TAG`
=> Byi fix bundler

README.md
Update document for https://github.com/SumoLogic/fluentd-output-sumologic/issues/47
FYI - @zhelyan @Trane9991
=> update doc for placeholders

lib/fluent/plugin/out_sumologic.rb, test/plugin/test_out_sumologic.rb
Addresses issue from https://github.com/SumoLogic/fluentd-output-sumologic/pull/54/files#r335225163 to add support for colons in the `sumo_key` hash tuple.
This seems to work since hash tuples in Ruby use the content as well: https://www.ruby-forum.com/t/how-to-use-tuple-as-hash-key/114797/2
We will need to make a new release and then update the gem dependency in our Dockerfile in the Kubernetes project.
=> Fix sumo_key hash tuple to support colons

lib/fluent/plugin/out_sumologic.rb, test/plugin/test_out_sumologic.rb
Expose `custom_fields` configuration parameter, which is going
to be merged with record's fields.
Example:
```ruby
record[:fields] = "foo=bar"
custom_fields = "lorem=ipsum"
```
is going to generate
```ruby
headers['X-Sumo-Fields']='foo=bar,lorem=ipsum'
```
=> Allow to add custom fields via config

lib/fluent/plugin/out_sumologic.rb, test/plugin/test_out_sumologic.rb
Add support for compression basing on logstash plugin
https://github.com/SumoLogic/logstash-output-sumologic/blob/master/lib/logstash/outputs/sumologic/compressor.rb
=> Add support for compression (gzip and deflate)

lib/fluent/plugin/out_sumologic.rb, test/plugin/test_out_sumologic.rb
It would be nice to add some dimensions directly from configuration.
`custom_dimensions` allows to add dimensions in `X-Sumo-Dimensions` header.
https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Metrics-to-an-HTTP-Source#supported-http-headers
=> Allow to set dimensions for metrics

CHANGELOG.md, lib/fluent/plugin/out_sumologic.rb
Fluentd in older versions (like 1.2.6) expects that configuration hashmap has no key rather than nil value
Fixes: #62
=> Fix configuration for older fluentd versions

README.md, lib/fluent/plugin/out_sumologic.rb
This exposes the httpclient send_timeout property to configuration by end-user. This can be useful when the user is receiving error messages like `#0 failed to flush the buffer. retry_time=0 next_retry_seconds=2021-07-20 17:26:24.606606697 +0000 chunk="REMOVED" error_class=HTTPClient::SendTimeoutError error="execution expired"` as the send_timeout can be increased until the chunk can be flushed.
=> Expose httpclient send_timeout

README.md, lib/fluent/plugin/out_sumologic.rb, test/plugin/test_out_sumologic.rb
Adds records_per_request on the top of retry changes. This is going to limit maximum number of records in request. This is because for bigger chunks, there is possibility to get send_timeout because of cancelling the request by receiver
=> feat(max_request_size): add max_request_size to limit size of requests

lib/fluent/plugin/out_sumologic.rb
Log warning if log key does not exist in the log
I decided to add warning message as raising exception may lead to re-ingest logs in current architecture
=> feat: log warning if log_key does not exist in log

fluent-plugin-sumologic_output.gemspec, vagrant/provision.sh
Removed bundler installation because bundler is shipped with the snap.
Removed the existing outdated gem version limitations from gemspec. This was necessary for the tests to pass.
=> chore(vagrant): upgrade Ruby to 3.3

lib/fluent/plugin/out_sumologic.rb, test/plugin/test_out_sumologic.rb
In v1.8.0, setting `compress` flag to either `true` or `false` caused compression to be enabled. This fixes multiple problems in the `configure` method of the plugin.
=> fix: fix how `compress` configuration flag works

.github/workflows/publish.yaml, CONTRIBUTING.md, fluent-plugin-sumologic_output.gemspec
Based on https://github.com/SumoLogic/logstash-output-sumologic/blob/v1.4.1/.github/workflows/publish.yml.
=> ci: publish on tag in CI

Vagrantfile, vagrant/README.md, vagrant/provision.sh
Add arm support
Install `ruby` from `apt` to provide matching `ruby-dev`
=> chore: add arm support to vagrant

README.md, lib/fluent/plugin/out_sumologic.rb
This exposes the `httpclient` receive_timeout property to be configurable by the end-user. This can be a useful setting to adjust when users hit errors like:
```
[warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2024-09-26 18:35:54 +0000 chunk="REDACTED" error_class=HTTPClient::ReceiveTimeoutError error="execution expired"
2024-09-26T18:35:52.924897251Z 2024-09-26 18:35:52.924711734 +0000 fluent.warn: {"retry_times":0,"next_retry_time":"2024-09-26 18:35:54 +0000","chunk":"REDACTED","error":"#<HTTPClient::ReceiveTimeoutError: execution expired>","message":"failed to flush the buffer. retry_times=0 next_retry_time=2024-09-26 18:35:54 +0000 chunk=\"REDACTED\" error_class=HTTPClient::ReceiveTimeoutError error=\"execution expired\""}
```
=> make receive_timeout configurable
